create table image(
	id int unsigned not null primary key auto_increment,
	title varchar(255) not null,
	image varchar(255) not null	
)engine=innodb default charset=utf8;

insert into image values
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/1.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/2.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/3.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/4.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/5.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/6.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/7.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/8.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/9.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/10.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/11.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/12.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/13.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/14.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/15.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/16.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/17.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/18.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/19.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/20.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/1.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/2.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/3.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/4.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/5.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/6.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/7.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/8.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/9.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/10.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/11.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/12.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/13.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/14.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/15.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/16.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/17.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/18.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/19.jpg'),
(null, '黄色毛呢格纹纽扣高腰长裙半裙', './uploads/20.jpg');